{{- $zonesMap := include "vm.per-zone.cluster.spec" . | fromYaml -}}
{{- range $name, $rolloutZone := $zonesMap }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  {{- with $rolloutZone.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end  }}
  name: {{ $name }}
  namespace: {{ include "vm.namespace" $ }}
  {{- $_ := set $ "zone" $rolloutZone }}
  {{- $_ := set $ "appKey" "zone" }}
  {{- $labels := fromYaml (include "vm.labels" $) }}
  {{- if $rolloutZone.clusterVersion }}
    {{- $_ := set $labels "app.kubernetes.io/version" $rolloutZone.clusterVersion }}
  {{- end }}
  labels: {{ toYaml $labels | nindent 4 }}
spec: {{ toYaml (deepCopy $rolloutZone) | nindent 2 }}
{{- end }}
